module.exports = [
  { "id": 1, "fact": "HTML is for content.", "by": "https://github.com/denisecase" },
  { "id": 2, "fact": "CSS is for style.", "by": "https://github.com/denisecase" },
  { "id": 3, "fact": "JavaScript is for logic.", "by": "https://github.com/denisecase" },
  { "id": 4, "fact": "TCP/IP was invented by Vint Cerf and Bob Kahn in 1974", "by": "https://github.com/mprogers" },
  { "id": 5, "fact": "Server-side apps can be written in numerous languages, including Java, JavaScript, Perl, PHP, Python, and, most recently, Swift", "by": "https://github.com/mprogers" },
  { "id": 6, "fact": "Node.js, invented by Ryan Dahl in 2009, originally ran only on Linux and macOS", "by": "https://github.com/mprogers" },
  { "id": 7, "fact": "A web application is a software application that runs on a remote server.", "by": "https://github.com/nandinidoppalapudi" },
  { "id": 8, "fact": "Nodejs is single threaded.", "by":"https://github.com/rahulreddy062"},
  { "id": 9, "fact": "Web server can refer to hardware or software, or both of them working together.", "by": "https://github.com/karanamvijaykumar" },
  { "id": 101},
  { "id": 102},
  { "id": 103},
  { "id": 104},
  { "id": 105, "fact": "PWA stands for Progressive Web App.", "by": "https://github.com/Logan11999"},
  { "id": 106},
  { "id": 107},
  { "id": 108},
  { "id": 109},
  { "id": 110},
  { "id": 111},
  { "id": 112},
  { "id": 113},
  { "id": 114},
  { "id": 115},
  { "id": 116},
  { "id": 117},
  { "id": 118},
  { "id": 119},
  { "id": 120},
  { "id": 121},
  { "id": 122},
  { "id": 123},
  { "id": 124},
  { "id": 201, "fact": "React is a widely used libaray.","by": "https://github.com/xchen182"},
  { "id": 202, "fact": "Working in the same project as other people can be messy", "by": "https://github.com/DCoop25"},
  { "id": 203, "fact": "JSON stores data in key-value pairs.", "by": "https://github.com/terry-woosley"},
  { "id": 204}, "fact": "JavaScript is not a part of Java programming", "by": "https://github.com/prasadbobbilla"},
  { "id": 205},
  { "id": 206, "fact": "WWW stands for World Wide Web", "by": "https://github.com/ayhalali" },
  { "id": 207},
  { "id": 208, "fact": "HTTPS works on port 443 and HTTP works on port 80", "by": "https://github.com/bharat-reddy-male"},
  { "id": 209},
  { "id": 210, "fact": "React is a java script library maintained by facebook and some other individual members.", "by": "https://github.com/abhiteja29" },
  { "id": 211, "fact": "JSON stands for JavaScript Object Notation", "by": "https://github.com/Echtniet"},
  { "id": 212, "fact": "In Javascript, an Array plus an Object equals an array of objects. An object plus an array equals 0.", "by": "https://github.com/mtburnes"},
  { "id": 213},
  { "id": 214, "fact": "The average lifespan of a website is 3 years", "by": "https://github.com/JacobTaylorNWMSU"},
  { "id": 215},
  { "id": 216},
  { "id": 217},
  { "id": 218},
  { "id": 219, "fact": "Angular is a platform for building mobile and desktop web applications.", "by": "https://github.com/prudhvi15"},
  { "id": 220, "fact": "PWA (Progressive Web App) is a responsive web app.", "by": "https://github.com/tanibi"},
  { "id": 221, "fact": "React is not a framework. It is a JavaScript library", "by": "https://github.com/aawajjoshi" },
  { "id": 222, "fact":"Progressive Web Apps are the recent innovation in technology. PWAs are an escape from the App Store.", "by":"https://github.com/suma-gitrep"},
  { "id": 223, "fact": "GitHub is a opensource version control system to store the code.", "by": "https://github.com/mohanpratapa" },
  { "id": 224},
  { "id": 401},
  { "id": 402},
  { "id": 403},
  { "id": 404},
  { "id": 405},
  { "id": 406},
  { "id": 407},
  { "id": 408},
  { "id": 409},
  { "id": 410},
  { "id": 411},
  { "id": 412},
  { "id": 413},
  { "id": 414},
  { "id": 415},
  { "id": 416},
  { "id": 417},
  { "id": 418},
  { "id": 419},
  { "id": 420},
  { "id": 421},
  { "id": 422},
  { "id": 423},
  { "id": 424},
]
